[package]
name = "app-service"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
serde = {  version  = "1.0.204", features = ["derive"]}
serde_json = "1.0.122"
xdgkit2 = "3.2.5"
freedesktop-icon-lookup = "0.1.3"
freedesktop_entry_parser = "1.3.0"
